version: "3.1"

services:
  db:
    image: mysql:5.7
    restart: always
    ports: 
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root

  # server:
  # // cвой имедж
  #   image:
  #   restart: always
  #   port: 8080:80
